### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by stereodenis** [modomoto/mina-tail#1]
```
be mina tail:live 
-----> Loading rbenv
tail: cannot open 'log/production.log' for reading: No such file or directory
tail: no files remaining
Connection to 78.155.217.82 closed.

 !     Command failed.
       Failed with status 1 (256)
be mina tail:live file=production.log
-----> Loading rbenv
tail: cannot open 'log/production.log' for reading: No such file or directory
tail: no files remaining
Connection to 78.155.217.82 closed.

 !     Command failed.
       Failed with status 1 (256)
```

**Comment by stereodenis** [comment]
why did you use `:app_path` ? Is it default configuration in mina?
If not — I think this should be added to Readme

**Comment by kat-crumbs** [comment]
Hi @stereodenis,

I don't think `app_path` is default configuration in mina, at least I could not find it. So you're right, it should probably be added to the Readme that it needs to be defined in the `deploy.rb` of your app.

I suppose it is used to make sure you're in the right directory, in case you have more than one app on your server. @Dahie can maybe explain better?

For now, try adding to your `deploy.rb`:

```
set :deploy_to,      "/var/www/foobar.com"
set :app_path,        "#{deploy_to}/#{current_path}"
```

Though maybe we can also change the occurrences of `app_path` in this project to `current_path`, as it seems it is pretty much the same as our `app_path`, see [here](https://github.com/mina-deploy/mina/blob/d62bd1d993c42e7c3b1fc213e62b94a4e7ad8241/tasks/mina/deploy.rb#L5) @Dahie ?

**Comment by Dahie** [comment]
I agree, didn't know about `current_path`, and it does what I need. I pushed a change in the repos, but I probably won't get around testing it before Monday. Thanks for the input! :)

**Comment by heragu** [comment]
I am still in the mail list xD could someone please remove ;-P
Am 09.07.2016 16:21 schrieb "Daniel Senff" notifications@github.com:

**Comment by stereodenis** [comment]
next time I will make PR. Thanks!
